name: 'Publish TS Library'
description: "Publish a typescript library"

inputs:
  node-version:
    required: false
    type: string
    default: '16'
  publish-token:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Setup git
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@syncwith'
    - run: yarn
      shell: bash
    - run: yarn build
      shell: bash
    - run: yarn publish --patch --verbose
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.publish-token }}
    - name: Push tag
      shell: bash
      run: |
        git push --follow-tags origin